Manage to support more loggers and better separation of middleware
mia-platform/glogger pull request #47
Opened 2023-06-08 16:01 UTC by davidebianchi

In this PR, I made a full refactor of the lib. The principal goal are:

* manage to support different loggers other than mux
* better routers middleware separation

2023-06-12 10:14 UTC, Danielecina approved these changes

2023-06-12 14:03 UTC, fredmaggiowski requested changes

2023-06-12 14:03 UTC, fredmaggiowski commented on internal/integration_test/fiber_mux_test.go
fiber logrus instead of fiber mux?

2023-06-12 17:55 UTC, davidebianchi commented on CHANGELOG.md
> +### Added
Yes, at the moment it's used the CHANGELOG. Anyhow, I would not migrate in this PR

2023-06-14 08:56 UTC, fredmaggiowski approved these changes

2023-06-14 08:56 UTC, merged